name: refi
description: "A Flutter movie recommendation mobile app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # HTTP client
  dio: ^5.3.0

  # State management
  provider: ^6.0.5

  # Navigation
  go_router: ^12.0.0

  # Local storage
  sqflite: ^2.3.0
  shared_preferences: ^2.2.0

  # Image handling
  cached_network_image: ^3.3.0

  # Environment variables
  flutter_dotenv: ^5.1.0

  # UI & Fonts
  google_fonts: ^6.1.0

  # Utilities
  intl: ^0.20.2
  url_launcher: ^6.2.0
  package_info_plus: ^8.0.0
  
  # File operations
  path_provider: ^2.1.0
  open_filex: ^4.4.0
  
  # YouTube player
  youtube_player_flutter: ^9.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
