// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzbuPqk6grO3Lnnnb7HPSjFp6rp-OfeOw',
    appId: '1:1068845308755:web:c2eab10afc59bf34345fa6',
    messagingSenderId: '1068845308755',
    projectId: 'refi-rekomendasi-film',
    authDomain: 'refi-rekomendasi-film.firebaseapp.com',
    storageBucket: 'refi-rekomendasi-film.firebasestorage.app',
    measurementId: 'G-FB3EW3RMVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn_6MHDyj44N5bP-QiVVnnBZPP_VFVBgM',
    appId: '1:1068845308755:android:7b1551f69ebcc235345fa6',
    messagingSenderId: '1068845308755',
    projectId: 'refi-rekomendasi-film',
    storageBucket: 'refi-rekomendasi-film.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf6uIM-eVVhjqZQoFtZ_LUSXm1P1vy2EY',
    appId: '1:1068845308755:ios:291b2f4898d64d01345fa6',
    messagingSenderId: '1068845308755',
    projectId: 'refi-rekomendasi-film',
    storageBucket: 'refi-rekomendasi-film.firebasestorage.app',
    iosBundleId: 'com.example.refi',
  );
}
